#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
		# set spacevim theme. by default colorscheme layer is not loaded,
		# if you want to use more colorscheme, please load the colorscheme
		# layer
		colorscheme = "wal"
		colorscheme_bg = "dark"
		# Disable guicolors in basic mode, many terminal do not support 24bit
		# true colors
		enable_guicolors = false
		# Disable statusline separator, if you want to use other value, please
		# install nerd fonts
		statusline_separator = "arrow"
		statusline_inactive_separator = "arrow"
		buffer_index_type = 4
		enable_tabline_filetype_icon = false
		enable_statusline_mode = false
		enable_cursorline = 0
		bootstrap_before = "myspacevim#before"
		bootstrap_after = "myspacevim#after"
		
		filemanager = "none"

		guifont = "Fira Code Retina 12"

[[custom_plugins]]
name = "dylanaraps/wal.vim"
merged = 0

[[custom_plugins]]
name = "Shougo/vimproc.vim"
merged = 0

[[custom_plugins]]
name = "guns/vim-sexp"
merged = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"
enable = false

[[layers]]
name = 'checkers'
enable = false

[[layers]]
name = 'shell'
default_position = 'top'
default_height = '100%'

[[layers]]
name = "fzf"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#lisp"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#vim"

[[layers]]
name = "sudo"

[[layers]]
name = "git"
